In [6]:

import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

Task 1. Scalar & Array Operations (Redo Section with Your Own Values):

In [7]:
#TASK 1
scalar = 3.7
arr = np.array([7, -5, 2, 1, 8, 4])

# Trigonometric functions
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))  # Normalized and Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)

# Exponential and logarithm
exp_values = np.exp(arr)
log_values = np.log(arr)  # Natural logarithm

# Absolute value and square root
abs_values = np.abs(arr)
sqrt_values = np.sqrt(arr)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(arr, 2)

# Rounding functions
round_values = np.round(arr)
floor_values = np.floor(arr)
ceil_values = np.ceil(arr)

# Display results
print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan:", atan_values)
print("exp:", exp_values)
print("log:", log_values)
print("abs:", abs_values)
print("sqrt:", sqrt_values)
print("rem:", rem_values)
print("round:", round_values)
print("floor:", floor_values)
print("ceil:", ceil_values)

sin: [ 0.6569866   0.95892427  0.90929743  0.84147098  0.98935825 -0.7568025 ]
cos: [ 0.75390225  0.28366219 -0.41614684  0.54030231 -0.14550003 -0.65364362]
tan: [ 0.87144798  3.38051501 -2.18503986  1.55740772 -6.79971146  1.15782128]
asin: [ 1.06543582 -0.67513153  0.25268026  0.12532783  1.57079633  0.52359878]
acos: [0.50536051 2.24592786 1.31811607 1.4454685  0.         1.04719755]
atan: [ 1.42889927 -1.37340077  1.10714872  0.78539816  1.44644133  1.32581766]
exp: [1.09663316e+03 6.73794700e-03 7.38905610e+00 2.71828183e+00
 2.98095799e+03 5.45981500e+01]
log: [1.94591015        nan 0.69314718 0.         2.07944154 1.38629436]
abs: [7 5 2 1 8 4]
sqrt: [2.64575131        nan 1.41421356 1.         2.82842712 2.        ]
rem: [1 1 0 1 0 0]
round: [ 7 -5  2  1  8  4]
floor: [ 7 -5  2  1  8  4]
ceil: [ 7 -5  2  1  8  4]


C:\Users\hasna\AppData\Local\Temp\ipykernel_32028\3668290609.py:15: RuntimeWarning: invalid value encountered in log
  log_values = np.log(arr)  # Natural logarithm
C:\Users\hasna\AppData\Local\Temp\ipykernel_32028\3668290609.py:19: RuntimeWarning: invalid value encountered in sqrt
  sqrt_values = np.sqrt(arr)


Task 2. 2×2 Matrix Calculations (Already Done in Class):

In [8]:
#TASK 2
matrix = np.array([[-1, 2], [7.2, -4],[5, np.sqrt(9)]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)

Matrix:
 [[-1.   2. ]
 [ 7.2 -4. ]
 [ 5.   3. ]]

sin:
 [[-0.84147098  0.90929743]
 [ 0.79366786  0.7568025 ]
 [-0.95892427  0.14112001]]

cos:
 [[ 0.54030231 -0.41614684]
 [ 0.60835131 -0.65364362]
 [ 0.28366219 -0.9899925 ]]

tan:
 [[-1.55740772 -2.18503986]
 [ 1.30462094 -1.15782128]
 [-3.38051501 -0.14254654]]

asine:
 [[-0.13933934  0.28148007]
 [ 1.57079633 -0.58903097]
 [ 0.76764752  0.42977543]]

acosine:
 [[1.71013567 1.28931625]
 [0.         2.1598273 ]
 [0.80314881 1.1410209 ]]

atangent:
 [[-0.78539816  1.10714872]
 [ 1.4327903  -1.32581766]
 [ 1.37340077  1.24904577]]

exp:
 [[3.67879441e-01 7.38905610e+00]
 [1.33943076e+03 1.83156389e-02]
 [1.48413159e+02 2.00855369e+01]]

log (natural):
 [[       nan 0.69314718]
 [1.97408103        nan]
 [1.60943791 1.09861229]]

abs:
 [[1.  2. ]
 [7.2 4. ]
 [5.  3. ]]

sqrt:
 [[       nan 1.41421356]
 [2.68328157        nan]
 [2.23606798 1.73205081]]

rem (remainder when divided by 2):
 [[1.  0. ]
 [1.2 0. ]
 [1.  1. ]]

round:
 [[-1.  

C:\Users\hasna\AppData\Local\Temp\ipykernel_32028\576662740.py:14: RuntimeWarning: invalid value encountered in log
  log_values = np.log(matrix)  # Natural logarithm (log base e)
C:\Users\hasna\AppData\Local\Temp\ipykernel_32028\576662740.py:18: RuntimeWarning: invalid value encountered in sqrt
  sqrt_values = np.sqrt(matrix)


Task 3. Apply the Same Operations on a 3×2 Matrix

In [9]:
#TASK 3

vec = np.array([1.5, 2, 7, 8, 5.5, -9, -2, 6.5])

# 1. Maximum value and index of max element
max_value = np.max(vec)
max_index = np.argmax(vec)  # Index of max element

# 2. Minimum value and index of min element
min_value = np.min(vec)
min_index = np.argmin(vec)  # Index of min element

# 3. Length of the vector
vec_length = len(vec)  # Equivalent to MATLAB's length()

# 4. Sorting in ascending order
sorted_vec = np.sort(vec)



# 5. Sum of elements
sum_values = np.sum(vec)

# 6. Product of elements
prod_values = np.prod(vec)

# 7. Median value
median_value = np.median(vec)

# 8. Mean value
mean_value = np.mean(vec)

# 9. Standard deviation
std_dev = np.std(vec)

# Display results
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Length of vector:", vec_length)
print("Sorted vector:", sorted_vec)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)

Max value: 8.0 at index 3
Min value: -9.0 at index 5
Length of vector: 8
Sorted vector: [-9.  -2.   1.5  2.   5.5  6.5  7.   8. ]
Sum of elements: 19.5
Product of elements: 108108.0
Median value: 3.75
Mean value: 2.4375
Standard deviation: 5.352788408857574


Task 4. Perform Same Operations on a 2×3 Matrix that has float values

In [10]:
#TASK 4
matrix = np.array([[-1.4, 2.6, 3.3], [7.2, -4, 5.5]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)

Matrix:
 [[-1.4  2.6  3.3]
 [ 7.2 -4.   5.5]]

sin:
 [[-0.98544973  0.51550137 -0.15774569]
 [ 0.79366786  0.7568025  -0.70554033]]

cos:
 [[ 0.16996714 -0.85688875 -0.98747977]
 [ 0.60835131 -0.65364362  0.70866977]]

tan:
 [[-5.79788372 -0.60159661  0.15974575]
 [ 1.30462094 -1.15782128 -0.99558405]]

asine:
 [[-0.19569105  0.36945913  0.47611906]
 [ 1.57079633 -0.58903097  0.86931785]]

acosine:
 [[1.76648738 1.2013372  1.09467727]
 [0.         2.1598273  0.70147848]]

atangent:
 [[-0.95054684  1.20362249  1.27656176]
 [ 1.4327903  -1.32581766  1.39094283]]

exp:
 [[2.46596964e-01 1.34637380e+01 2.71126389e+01]
 [1.33943076e+03 1.83156389e-02 2.44691932e+02]]

log (natural):
 [[       nan 0.95551145 1.19392247]
 [1.97408103        nan 1.70474809]]

abs:
 [[1.4 2.6 3.3]
 [7.2 4.  5.5]]

sqrt:
 [[       nan 1.61245155 1.81659021]
 [2.68328157        nan 2.34520788]]

rem (remainder when divided by 2):
 [[0.6 0.6 1.3]
 [1.2 0.  1.5]]

round:
 [[-1.  3.  3.]
 [ 7. -4.  6.]]

floor:
 [[-

C:\Users\hasna\AppData\Local\Temp\ipykernel_32028\3734580539.py:14: RuntimeWarning: invalid value encountered in log
  log_values = np.log(matrix)  # Natural logarithm (log base e)
C:\Users\hasna\AppData\Local\Temp\ipykernel_32028\3734580539.py:18: RuntimeWarning: invalid value encountered in sqrt
  sqrt_values = np.sqrt(matrix)
